
#      spring.cloud.config.label：配置仓库的分支
#      spring.cloud.config.server.git.uri：配置 Git 仓库地址（GitHub、GitLab、码云 ...）
#      spring.cloud.config.server.git.search-paths：配置仓库路径（存放配置文件的目录）
#      spring.cloud.config.server.git.username：访问 Git 仓库的账号
#      spring.cloud.config.server.git.password：访问 Git 仓库的密码

#要改端口的时候要重新写一个配置文件bootstrap.properties；这里面写，这个配置文件是优先加载的
#server.port=

spring:
  application:
    name: kmvc-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/topsale/spring-cloud-config #git的访问路径
          search-paths: respo  #git项目目录
          username: #用户名：登录名
          password: #登录密码
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
