#  spring.cloud.config.uri：配置服务中心的网址
#    spring.cloud.config.name：配置文件名称的前缀
#    spring.cloud.config.label：配置仓库的分支
#    spring.cloud.config.profile：配置文件的环境标识
#    dev：表示开发环境
#    test：表示测试环境
#    prod：表示生产环境
spring:
  application:
    name: hello-spring-cloud-config-client
  cloud:
    config:
      uri: http://localhost:8888
      name: config-client
      label: master
      profile: dev

server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/