spring:
  application:
    name: kmvc-spring-cloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false

spring:
  zipkin:
    base-url: http://localhost:9411